### ISSUE TITLE
Feature request: allow for translatable Snippets

### ISSUE THREAD

**Issue by mvdkleijn** [wolfcms/wolfcms#446]
Implement translatable Snippets. See my solution below.

From issue #415

> the includeSnippet() sending an event out, which is picked up by the multi_lang plugin that then 
> responds back which language version of the Snippet should be used.

**Comment by godDLL** [comment]
That's actually a great idea.
Let me go ahead and fork you, while the wolf sleeps.

**Comment by mvdkleijn** [comment]
Instead of doing something non constructive as forking, maybe simply contributing a pull request for this and/or bugs would be better. Since that would a) help me and b) help the rest of the users.

Seems a lot more constructive than your comment.

**Comment by godDLL** [comment]
This has been here for longer than is reasonable. And off course, if what I have in mind will come out any good I'll adapt it upstream.

On Thu, Jul 28, 2016 at 10:21 am, Martijn < notifications@github.com [notifications@github.com] > wrote:
Instead of doing something non constructive as forking, maybe simply contributing a pull request for this and/or bugs would be better. Since that would a) help me and b) help the rest of the users.

Seems a lot more constructive than your comment.
